### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by Fuhan1994** [DetectionTeamUCAS/FPN_Tensorflow#100]
作者您好，想问一下单个GPU1080ti训练，10step1s多是否正常呢（训练10000步需要2小时左右）

**Comment by yangxue0827** [comment]
检查是否调用了gpu，你这个像是没用到gpu的速度 @Fuhan1994

**Comment by Fuhan1994** [comment]
显示是
 Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:21:00.0, compute capability: 6.1)

**Comment by ttianwang** [comment]
你好，我想问一下你训练图片多大呢，大概占多少内存呢 @Fuhan1994

**Comment by Fuhan1994** [comment]
> 你好，我想问一下你训练图片多大呢，大概占多少内存呢 @Fuhan1994

训练图片512*512，80-200kb之间。

**Comment by ttianwang** [comment]
嗯嗯，我训练的图片是1024*1024的，然后是我表达错误了，训练的时候我显存占用8个g，请问您大概是多少？

**Comment by ttianwang** [comment]
> > 你好，我想问一下你训练图片多大呢，大概占多少内存呢 @Fuhan1994
> 
> 训练图片512*512，80-200kb之间。

嗯嗯，我训练的图片是1024*1024的，然后是我表达错误了，训练的时候我显存占用8个g，请问您大概是多少？

**Comment by Fuhan1994** [comment]
> > > 你好，我想问一下你训练图片多大呢，大概占多少内存呢 @Fuhan1994
> > 
> > 
> > 训练图片512*512，80-200kb之间。
> 
> 嗯嗯，我训练的图片是1024*1024的，然后是我表达错误了，训练的时候我显存占用8个g，请问您大概是多少？

> > > 你好，我想问一下你训练图片多大呢，大概占多少内存呢 @Fuhan1994
> > 
> > 
> > 训练图片512*512，80-200kb之间。
> 
> 嗯嗯，我训练的图片是1024*1024的，然后是我表达错误了，训练的时候我显存占用8个g，请问您大概是多少？

大概也是8G。我发现现在训练是正常的（10step0.6s），可能是cuda环境配置的问题，刚刚重新配置过。也是尝试了很久一直找不到原因。感谢帮助！

**Comment by ttianwang** [comment]
我一直是1s左右10次，这个时间上我没有太注意，不太好意思 @Fuhan1994
