### ISSUE TITLE
how could I run inference on single image

### ISSUE THREAD

**Issue by CoinCheung** [DetectionTeamUCAS/FPN_Tensorflow#103]
Hi, 

Thanks for providing this great implementation, I am trying to use your code to run inference on one single jpg image. I notice that the inference code requires the images stored in some folder ahead of launching the inference code. How could I run inference on single jpeg image from memory as an input variable?

**Comment by yangxue0827** [comment]
fix this [variable](https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/inference.py#L83)
