### ISSUE TITLE
结果不能复现

### ISSUE THREAD

**Issue by ttianwang** [DetectionTeamUCAS/FPN_Tensorflow#104]
你好，我想问一下，你们训练网络的配置是怎样的？还有我现在遇到一个很奇怪的问题，就是同一个数据集，同样的代码，什么都没改，但就是两次跑出来的结果很差，能差5%-7%，按理说不应该出现这种状况的，想请问你一下，就是你们遇到过这样的问题吗？你们每次的结果都是差不多的吗？

**Comment by chanshibing** [comment]
> 你好，我想问一下，你们训练网络的配置是怎样的？还有我现在遇到一个很奇怪的问题，就是同一个数据集，同样的代码，什么都没改，但就是两次跑出来的结果很差，能差5%-7%，按理说不应该出现这种状况的，想请问你一下，就是你们遇到过这样的问题吗？你们每次的结果都是差不多的吗？

你好想问一下 你跑的是voc2007吗

**Comment by yangxue0827** [comment]
我训练时基本差不太多 @ttianwang
