### ISSUE TITLE
你好，我想把模型部署到移动端.

### ISSUE THREAD

**Issue by siyangbing** [DetectionTeamUCAS/FPN_Tensorflow#105]
我尝试将模型转换为lite文件，但是在转换过程中显示不支持逻辑运算符．我想知道如何把模型部署到android端．是否支持把模型压缩为移动端可以使用的模型．对此有什么好的建议吗？

**Comment by yangxue0827** [comment]
抱歉，我不懂这方面的技术 @siyangbing

**Comment by siyangbing** [comment]
你好，你的模型对小目标检测准确率非常高，但是我想把模型压缩一下，因为现在推断速度有点慢，我想做到一秒以内，有什么好的建议吗？非常感谢！

**Comment by yangxue0827** [comment]
难道现在不在1秒以内？你不用gpu是吗？ @siyangbing

**Comment by siyangbing** [comment]
你好，用GPU是可以，我想把他部署到linux终端，例如树莓派上．我就是想问一下模型还有优化的空间吗？比如去掉一些没有用的权重参数．毕竟现在的模型太大了．非常感谢

**Comment by yangxue0827** [comment]
用小一点的backbone、FPN那部分通道数可以砍一下，还有anchor的数量（如果是小目标的话，P5-P6可以不用），精度肯定会下降，需要你自己平衡了 @siyangbing

**Comment by siyangbing** [comment]
好的，非常感谢

**Comment by HUI11126** [comment]
> 我尝试将模型转换为lite文件，但是在转换过程中显示不支持逻辑运算符．我想知道如何把模型部署到android端．是否支持把模型压缩为移动端可以使用的模型．对此有什么好的建议吗？

请问，你部署成功了吗？我也遇到不支持的运算符
