### ISSUE TITLE
关于最终检测框

### ISSUE THREAD

**Issue by ttianwang** [DetectionTeamUCAS/FPN_Tensorflow#107]
你好，我看到最后的检测框，您是将所有得到的检测框都作为每一类的检测框，但不应该是，检测框对应的得分最高的类别才是该检测框对应的类别吗

**Comment by yangxue0827** [comment]
代码会对每个proposal都预测每一类的置信分以及对应的预测框，最后通过卡阈值过滤。 @ttianwang
