### ISSUE TITLE
训练过程出现Nan

### ISSUE THREAD

**Issue by TVXQ20031226** [DetectionTeamUCAS/FPN_Tensorflow#11]
你好，我利用您这份代码训练时出现了nan，应该不是数据的问题，因为我之前根据您另一份代码训练时成功的，tfrecord也是在那一份代码上就生成好的，但这份代码大概训练2800次以后loss就出现nan了，望解答谢谢~

**Comment by yangxue0827** [comment]
voc数据的话，用默认参数应该不会出现nan，自己的数据集的话可能需要调参啦。 @TVXQ20031226

**Comment by TVXQ20031226** [comment]
我是训练自己的数据集，用的参数是之前在您发布的另一份代码中测试过的，但是在这份代码中就出现了nan。。。
@yangxue0827

**Comment by yangxue0827** [comment]
调参吧 @TVXQ20031226
