### ISSUE TITLE
关于tensorboard的问题

### ISSUE THREAD

**Issue by wytcsuch** [DetectionTeamUCAS/FPN_Tensorflow#114]
您好，我看了您的代码，每隔10个iter保存一次summary，因为我训练了80000iter，按道理应该保存了8000次images，但是打开tensorboard只可视化9个step的images。实际上整个summary的大小有9g多，应该是保存了很多images，那么有没有什么办法可以可视化所有的images呢？

**Comment by yangxue0827** [comment]
这个是tensorboard的机制，东西保存了的，但在浏览器看的时候就只能间隔展示。我也不清楚怎么解决，抱歉。
