### ISSUE TITLE
关于验证集val_loss的问题

### ISSUE THREAD

**Issue by LLLhp** [DetectionTeamUCAS/FPN_Tensorflow#116]
大神您好！
我刚接触目标检测不久，你们的开源资料帮助了我很多。最近在用你们的FPN和Cascade_FPN跑自己的数据集，通过tensorboard查看了训练日志，看到了train_loss的变化。
现在想请问大神，这份代码能不能查看验证集、即val_loss的变化情况？我想通过验证集看自己训练的过拟合程度，再进一步尝试调参。
希望大神百忙之中抽空回复一下我的问题，非常感谢~

**Comment by yangxue0827** [comment]
肯定是可以的，你在跑val的时候注意关掉梯度反传就行。 @LLLhp

**Comment by LLLhp** [comment]
好的！我现在试一下。谢谢大神~
