### ISSUE TITLE
convert_data_to_tfrecord.py makes huge GB space

### ISSUE THREAD

**Issue by pratikshaya** [DetectionTeamUCAS/FPN_Tensorflow#117]
I have 17GB of  JPEGimages and xml file. However if i convert it into tfrecord it becomes 191GB. Due to huge GB data I got the following error while training.
![Capture](https://user-images.githubusercontent.com/26374302/68991203-87d61d00-089f-11ea-87a7-a60321323783.PNG)

**Comment by yangxue0827** [comment]
you can use placeholder function, like this [train_with_placeholder.py](https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/train_with_placeholder.py), so that you do not need tfrecord.
@pratikshaya
