### ISSUE TITLE
how to freeze the model

### ISSUE THREAD

**Issue by shahmustafa** [DetectionTeamUCAS/FPN_Tensorflow#118]
Hi...how we can freeze the model to .pb? 

I tried Tensorflow-object-detection's [export_inference_graph.py](https://github.com/tensorflow/models/blob/master/research/object_detection/export_inference_graph.py) script, it is throwing `Key Conv/biases not found in checkpoint
`
 and to try TensorFlow's [freeze_grapgh..py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py), it requires output node names

do you know any solution for this, @yangxue0827 @yangJirui

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/FPN_Tensorflow/tree/master/libs/export_pbs
@shahmustafa
