### ISSUE TITLE
important bug

### ISSUE THREAD

**Issue by guker** [DetectionTeamUCAS/FPN_Tensorflow#124]
https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/9ea554665a127af72698ed7e3bedd5a3fd5db253/libs/box_utils/anchor_utils.py#L74
应该改为如下：
```python
return ws, hs
```

**Comment by yangxue0827** [comment]
谢谢提醒，因为anchor是对称的，所以这个对结果影响不大。

**Comment by guker** [comment]
> 谢谢提醒，因为anchor是对称的，所以这个对结果影响不大。

是的，在voc/coco上，一般设置都是对称的，在其他任务，比如行人检测，ratios可能不是对称的
