### ISSUE TITLE
The code of gtboxes is wrong. How to solve this problem? Thank you first.

### ISSUE THREAD

**Issue by StrongBirds** [DetectionTeamUCAS/FPN_Tensorflow#14]
![problem](https://user-images.githubusercontent.com/38725814/49871132-5b747e00-fe50-11e8-95e4-aa20e44dacfe.png)

**Comment by yangxue0827** [comment]
you have the coordinates reversed @StrongBirds

**Comment by StrongBirds** [comment]
> you have the coordinates reversed @StrongBirds
The coordinates of my tfrecord file are reversed. Thank you very much for your quick reply.
