### ISSUE TITLE
anchor_target_layer

### ISSUE THREAD

**Issue by JiXuKong** [DetectionTeamUCAS/FPN_Tensorflow#140]
你好，请问一下，python 版本的anchor_target_layer和tf版本的anchor_target_layer最后效果上会有差别吗，因为早些时候发现你们的这部分代码是用tf写的，然后我试了一下好像eval效果不太好

**Comment by yangxue0827** [comment]
这个不太清楚了，用python是方便调试，这部分不涉及梯度
