### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by EvaneSnow** [DetectionTeamUCAS/FPN_Tensorflow#150]
你好，我使用train.py训练时，程序加载完了cuda,cudnn等库后，开始打印损失值前，代码就卡住啦，一直不运行，也不报错，这是什么问题呢？

**Comment by EvaneSnow** [comment]
@yangxue0827

**Comment by yangxue0827** [comment]
tfrecord里没有数据是空的

**Comment by EvaneSnow** [comment]
衷心感谢你，我之前做的tfrecord是有数据的，不知道为啥重新做下，又没有啦，又重弄了哈，又有数据啦，谢谢。
