### ISSUE TITLE
您好，关于最大迭代次数的疑问。

### ISSUE THREAD

**Issue by yooyo-Q** [DetectionTeamUCAS/FPN_Tensorflow#158]
您好，我使用这个算法进行4目标检测任务，总共1000张图片。按照最大迭代次数300来设置的话，模型没有收敛，但是效果还行。最大迭代次数设置为1000，即1 epoc，四目标中3目标精度特别高，还有1个目标精度很低。不知道您在设置最大迭代次数的时候是怎么考虑的呢？

**Comment by yangxue0827** [comment]
你按照你自己的数据集调整到最佳值就行。
