### ISSUE TITLE
测试时导入同一个checkpoint测试结果不一样

### ISSUE THREAD

**Issue by TVXQ20031226** [DetectionTeamUCAS/FPN_Tensorflow#17]
训练完以后导入同一个checkpoint 发现每次的结果都不一样，看了下eval.py代码
![image](https://user-images.githubusercontent.com/33944995/50065104-aba46500-01ef-11e9-9d9d-4f460f58caf6.png)

sess.run(tf.global_variables_initializer())

这样导致，载入的checkpoint的数据失效，所有数据重新进行了初始化，导致模型是个随机的取值，从而每次运行获得的结果不同。

想问下您这个是不是有点小问题啊。。。。望解答谢谢~~~

**Comment by yangxue0827** [comment]
代码应该是没有问题的，可能是没找到你的权重，检查一下路径 @TVXQ20031226

**Comment by AtTops** [comment]
应该是没找到你的权重:
FPN_Tensorflow/libs/networks/build_whole_network.py中的get_restorer():

注意VERSION和TRAINED_CKPT,与你下载的检查点（https://github.com/DetectionTeamUCAS/Models/tree/master/FPN_Tensorflow）的文件夹路径的匹配。
@TVXQ20031226

unrar mutil rar files:
unrar x FPN_Res101_20181201.part1.rar
