### ISSUE TITLE
您好，请问整体的网络结构图可以这样表示吗？

### ISSUE THREAD

**Issue by lilmangolil** [DetectionTeamUCAS/FPN_Tensorflow#19]
看tensorboard中的网络结构图有些看不懂，感谢您的指导~
![fpn](https://user-images.githubusercontent.com/45140199/50196215-54cc9600-037d-11e9-844e-ca834fdf6f80.jpg)

**Comment by lilmangolil** [comment]
这个是https://github.com/unsky/FPN
里面的结构图~

**Comment by yangxue0827** [comment]
结构是一样的，不用看tensorboard，不如看代码。 @lilmangolil

**Comment by yangxue0827** [comment]
你好，这个代码和https://github.com/unsky/FPN的结构图不一样，我之前没仔细看，upsampling的应该从sum之后直接输入，而不是从p层输入。 @lilmangolil
