### ISSUE TITLE
Download trained model by this project,but it doesn't work!

### ISSUE THREAD

**Issue by 1451595897** [DetectionTeamUCAS/FPN_Tensorflow#2]
Thank you for your recommendation of the improved code，but when I replay this code,I found a problem.
![image](https://user-images.githubusercontent.com/39090271/49359692-ded7f600-f711-11e8-94ec-73e0f9830fa1.png)
![image](https://user-images.githubusercontent.com/39090271/49359719-f57e4d00-f711-11e8-8615-ba02f3f78fbf.png)
@yangxue0827

**Comment by yangxue0827** [comment]
I haven't uploaded it yet. @1451595897

**Comment by 1451595897** [comment]
你好，我发现我还是出现之前的问题的，就是tfrecords一直生成不了，想请教一下你的，我不知道路径哪里出现问题了！ @yangxue0827 
![default](https://user-images.githubusercontent.com/39090271/49373338-bc0d0800-f738-11e8-9626-6b5d47fd5ef7.png)
![default](https://user-images.githubusercontent.com/39090271/49373270-5b7dcb00-f738-11e8-9a74-1feda35e93b3.png)
![default](https://user-images.githubusercontent.com/39090271/49373290-8831e280-f738-11e8-9880-5082bab3c1ac.png)

**Comment by lilmangolil** [comment]
> 你好，我发现我还是出现之前的问题的，就是tfrecords一直生成不了，想请教一下你的，我不知道路径哪里出现问题了！ @yangxue0827
> ![default](https://user-images.githubusercontent.com/39090271/49373338-bc0d0800-f738-11e8-9626-6b5d47fd5ef7.png)
> ![default](https://user-images.githubusercontent.com/39090271/49373270-5b7dcb00-f738-11e8-9a74-1feda35e93b3.png)
> ![default](https://user-images.githubusercontent.com/39090271/49373290-8831e280-f738-11e8-9880-5082bab3c1ac.png)

你可以试一下运行时把--xml_dir和--image_dir两个语句去掉试一下

**Comment by yangxue0827** [comment]
--xml_dir的值写错了，少了s

**Comment by 1451595897** [comment]
@yangxue0827 你好，之前的问题已经解决了，但测试的时候又出现了新的问题，我用的是cuda8.0,tensorflow1.3版本的。提示：tensorflow.python.framework.errors_impl.InternalError: TopKOp: Could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to sort input, temp_storage_bytes: 1201407, status: invalid configuration  argument
![default](https://user-images.githubusercontent.com/39090271/49574203-cfa7b100-f97a-11e8-8e08-5f0155865920.png)
![default](https://user-images.githubusercontent.com/39090271/49574251-e9e18f00-f97a-11e8-91e9-05672139d164.png)

**Comment by wangcm12** [comment]
@1451595897  你好，我也是出现数据生成不了tfrecords，请问你怎么解决的?谢谢
