### ISSUE TITLE
map!

### ISSUE THREAD

**Issue by 1451595897** [DetectionTeamUCAS/FPN_Tensorflow#22]
你好，我把VOC2007数据集按照8:2的比例分成训练集和测试集，按照你的训练过程训练了150000次，最后得到的map为0.804，这结果与你训练测试的结果相差比较大的，我想知道，是否是我哪里出现问题了？
![default](https://user-images.githubusercontent.com/39090271/50370069-ec7af000-05da-11e9-93ce-5105294621f9.png)

**Comment by yangxue0827** [comment]
voc2007有自己的测试数据，不需要自己去划分 @1451595897

**Comment by 1451595897** [comment]
明白了，我是把9963张VOC2007图像重新按8:2的比例划分训练集和测试集，这样的话，我就把训练集的数量增加了（相比原来的5000多张），所以最后的性能会有所提升，对吧？ @yangxue0827

**Comment by yangxue0827** [comment]
对的 @1451595897
