### ISSUE TITLE
运行inference.py 测试时，运行的检测结果没有检测框。

### ISSUE THREAD

**Issue by gm0515** [DetectionTeamUCAS/FPN_Tensorflow#24]
您好，我们使用您提供的”voc_149999model.ckpt.data-00000-of-00001“作为权重文件，用于检测demos文件夹的测试图片。但是最终的运行结果显示，根本没有进行检测，即测试图像中不存在检测框。

或者说，您的代码是如何调用权重文件的？

**Comment by rw1995** [comment]
我也遇到了同样的问题，请问您是如何解决的

**Comment by chaoswong1981** [comment]
项目没清楚，下载下来的 voc_149999model.ckpt.data-00000-of-00001 这样的权值文件是需要放在 $PATH_ROOT/output/trained_weights 目录下才行的。
@rw1995
