### ISSUE TITLE
关于eval的precision

### ISSUE THREAD

**Issue by summerrr** [DetectionTeamUCAS/FPN_Tensorflow#26]
为什么最后结果的precision那么小呢，我看论文中也都挺大的啊，是还要再计算什么嘛

**Comment by yangxue0827** [comment]
我输出的是数组最后一个数，p当然是
最小的，r是最大的。 @summerrr

**Comment by summerrr** [comment]
那应该输出什么啊，看有的论文只有展示这个，是都取最大的？

**Comment by yangxue0827** [comment]
卡阈值，然后取最后一组 @summerrr
