### ISSUE TITLE
您好，我在12+07上训练得到的效果没有你展示效果好，这是什么原因。

### ISSUE THREAD

**Issue by StrongBirds** [DetectionTeamUCAS/FPN_Tensorflow#27]
![000348](https://user-images.githubusercontent.com/38725814/50671519-682e6100-100d-11e9-9f49-e9ae02043921.jpg)
![000449](https://user-images.githubusercontent.com/38725814/50671520-682e6100-100d-11e9-84d7-34e2db4e3119.jpg)
![004029](https://user-images.githubusercontent.com/38725814/50671521-682e6100-100d-11e9-8b79-f3de74e8b45e.jpg)
恳请您的指点。

**Comment by yangxue0827** [comment]
看图我也不清楚什么情况，但是有人跑过，大概80的mAP， [参考这里](https://github.com/yangxue0827/FPN_Tensorflow/issues/46#issuecomment-446210993)。

**Comment by StrongBirds** [comment]
> 看图我也不清楚什么情况，但是有人跑过，大概80的mAP， [参考这里](https://github.com/yangxue0827/FPN_Tensorflow/issues/46#issuecomment-446210993)。
我在07+12上训练在07上测试准确率是82.1%，但是测试的图片是上面的情况。

**Comment by yangxue0827** [comment]
你是不是把图片通道弄反了，我看你的图颜色是反的 @StrongBirds

**Comment by StrongBirds** [comment]
> 你是不是把图片通道弄反了，我看你的图颜色是反的 @StrongBirds

我也发现了这个问题，你的test.py代码我没有动，直接拿过来用的，请问是什么原因造成的，感谢您这么迅速的回复。

**Comment by yangxue0827** [comment]
应该是我存图存反了，你试试测试一下其他图片，可能这几张图在你训练的model下效果就是不好。 @StrongBirds

**Comment by StrongBirds** [comment]
> 应该是我存图存反了，你试试测试一下其他图片，可能这几张图在你训练的model下效果就是不好。 @StrongBirds

谢谢您，我自己尝试修改一下。

**Comment by StrongBirds** [comment]
您好，之前图片通道问题导致demo的图片颜色不对，代码在test.py的90行改成
cv2.imwrite(inference_save_path + '/' + nake_name,
                        final_detections[:, :, :])就可以了
还有是在60行代码改成
feed_dict={img_plac: raw_img[:, :, ::-1]
在运行demo时就可以实现您展示的效果了，再次感谢您提供的代码
