### ISSUE TITLE
您好，在训练过程中发现真实结果的标签错位，请问是什么原因？

### ISSUE THREAD

**Issue by lilmangolil** [DetectionTeamUCAS/FPN_Tensorflow#3]
您好，从tensorboard中观察预测结果与真实结果的对比，发现真实结果的框出现的错位的情况，请问是什么原因呢？

**Comment by 1451595897** [comment]
你好，想问一下你的，你复现代码的时候，那个trained model你可以顺利下载下来吗？ @lilmangolil

**Comment by lilmangolil** [comment]
> 你好，想问一下你的，你复现代码的时候，那个trained model你可以顺利下载下来吗？ @lilmangolil

你好，我没有下载那个模型，直接用resnet的预训练模型训练的。

**Comment by yangxue0827** [comment]
给个图例 @lilmangolil

**Comment by lilmangolil** [comment]
> 给个图例 @lilmangolil
您好，比如这两张图，标记的应该是人脸。这个数据库应该是没问题的，之前训练时没有出现过这个问题，感谢您的回复！
![1543830986 1](https://user-images.githubusercontent.com/45140199/49366807-421f5380-f725-11e8-8722-22b1d7e8c979.png)
![1543831244 1](https://user-images.githubusercontent.com/45140199/49366882-6ed36b00-f725-11e8-87cb-3f57315f6978.png)

**Comment by yangxue0827** [comment]
你的xy坐标是不是写反了 @lilmangolil

**Comment by lilmangolil** [comment]
> 你的xy坐标是不是写反了 @lilmangolil

您好，我又重新将数据库转化成了tfrecord，然后标签就没有错位了，可能是转化过程中出的问题吧。感谢您的回复~
