### ISSUE TITLE
no modul named tfplot

### ISSUE THREAD

**Issue by lo-pan** [DetectionTeamUCAS/FPN_Tensorflow#30]
楼主，我在ubuntu系统上用pycharm创建虚拟环境打开工程，然后tensorflow-plot这个包也在配置环境里下载了，也安装成功了，但是运行demo的时候提示
                                File “../libs/networks/resnet.py”,line 12 ,in <module>
               ImportError: No module named tfplot
这是什么原因呢，请作者指教一下，谢谢！

**Comment by yangxue0827** [comment]
确认一下是否装在虚拟环境下了，实在解决不了的相关可视化代码可以注释。 @lo-pan

**Comment by lo-pan** [comment]
好的，我去试试，谢谢楼主

**Comment by lo-pan** [comment]
楼主，你的程序不能在mobilenet的模型上测试图片吗？我修改了cfgs文件代码，总是提示出错

**Comment by yangxue0827** [comment]
mobilenet的我没有改，需要自己改一下代码 @lo-pan

**Comment by lo-pan** [comment]
好的， 谢谢楼主回复！ @yangxue0827

**Comment by ttianwang** [comment]
你好，我也出现了这个问题，我想问一下这是哪个包啊，我的环境里面没有这个，但是下载的话也不知道是下载什么
