### ISSUE TITLE
您好，我在运行eval文件的时候报了一个很奇怪的错误。

### ISSUE THREAD

**Issue by yangye19960922** [DetectionTeamUCAS/FPN_Tensorflow#33]
我配置了image和annotation的路径，然后运行了py文件，具体的错误如下：
InternalError (see above for traceback): WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
服务器配置是 cuda8+tf1.4

**Comment by yangxue0827** [comment]
试一下cfgs.py 里的CUDA9=Fasle
@yangye19960922
