### ISSUE TITLE
您好，在训练自己的数据集过后运行eval.py进行测试，发现Precison这一指标很低，最高是0.18

### ISSUE THREAD

**Issue by lilmangolil** [DetectionTeamUCAS/FPN_Tensorflow#35]
在看您在cfg.py中所写的在VOC数据集上面的测试结果，Precison这一指标也不高，请问这是什么原因呢？如何操作可以提高这一值？非常感谢(｡◕◡◕｡)ﾉ

**Comment by yangxue0827** [comment]
我输出的是矩阵的最后一维，根据pr曲线，p值当然是最低的。 @lilmangolil
