### ISSUE TITLE
您好，有一些问题想问一下

### ISSUE THREAD

**Issue by ttianwang** [DetectionTeamUCAS/FPN_Tensorflow#42]
您好，我看您的对比实验中改了SHARE_NET ，SHORT_SIDE_LEN ，  FAST_RCNN_MINIBATCH_SIZE这几个参数的值，您这么改的理由是什么啊，还有就是您有发表一些相关的论文吗，想看一看

**Comment by ttianwang** [comment]
我还有一个问题，就是我测试的时候，我的图片一般就会缩小，并且还变蓝了，请问这是什么原因啊
![000144](https://user-images.githubusercontent.com/42958432/51458044-c178ed00-1d8e-11e9-99d3-144b2a6ea88f.jpg)

**Comment by yangxue0827** [comment]
变蓝是通道存反了，你改一下就行，缩小是输入网络时进行了尺度变换，如果要画在原图，你需要自己根据尺度变换的scale对box进行变换一下。 @ttianwang

**Comment by yangxue0827** [comment]
论文看FPN论文，这个代码是复现。 @ttianwang

**Comment by ttianwang** [comment]
好的，谢谢，还有就是您改动的几个参数也是比照FPN论文中进行的改动吗

**Comment by yangxue0827** [comment]
部分是的，只是一些调参实验 @ttianwang

**Comment by ttianwang** [comment]
好的，谢谢谢谢

**Comment by rw1995** [comment]
> 好的，谢谢谢谢

不好意思，请问一下您，我在运行提供的ｄｅｍｏ时候，发现出来的图片中没有检测框？请问你是怎么解决的　？

**Comment by yangxue0827** [comment]
检查是否加载了权重 @rw1995
