### ISSUE TITLE
请问为什么运行完eval或者inference后图片的颜色变了

### ISSUE THREAD

**Issue by fatSister** [DetectionTeamUCAS/FPN_Tensorflow#44]
楼主你好，我发现运行完eval或者inference后，得到的标注后图片的颜色跟原图不一样了，请问是哪个地方造成的啊？画了锚框的图片明显比原图更亮

**Comment by yangxue0827** [comment]
cv2存图存反了，你取反一下就好 @fatSister

**Comment by fatSister** [comment]
楼主，你说的存反的地方具体是指哪呀？我改了draw_boxex_with_label_and_scores函数中的img_array=np.array(img_array*255/np.max(img_array),dtype=np.unit8)，把这一句改成img_array=np.array(img_array,dtype=np.unit8)，然后图片颜色一致了
