### ISSUE TITLE
feature c2

### ISSUE THREAD

**Issue by chengjunjiecn** [DetectionTeamUCAS/FPN_Tensorflow#45]
feature_dict = {'C2': end_points_C2['{}/block1/unit_2/bottleneck_v1'
C2的选择，为什么用 unit_2/bottleneck_v1？ 可以用unit_3吗

**Comment by yangxue0827** [comment]
C2的大小变了，你需要看一下这里的resnet实现，有点不一样 @chengjunjiecn
