### ISSUE TITLE
请问resnet.py里面的C2，C3，C4为什么跟P2，P3, P4的尺寸不一样

### ISSUE THREAD

**Issue by fatSister** [DetectionTeamUCAS/FPN_Tensorflow#46]
在Tensorboard里面看到的Layer2/C2_heat与Layer2/P2_heat的height和width不一样，请问这个C2,C3,C4具体指的是什么啊？

**Comment by yangxue0827** [comment]
这个需要你自己看一下resnet的实现，有点调整 @fatSister

**Comment by Rachquazar** [comment]
I have gone through the code. I am not able to understand how does the shape of P4, p3, p2 come out be greater than the respective sizes of C4,C3,C2
