### ISSUE TITLE
Skipping cancelled enqueue attempt with queue not closed

### ISSUE THREAD

**Issue by 1451595897** [DetectionTeamUCAS/FPN_Tensorflow#48]
你好，我再重新跑一次这个代码的时候，在训练到9991次的时候，发现了这个错误，里面有一个警告提示是：Skipping cancelled enqueue attempt with queue not closed，紧接着后面就崩了。
![default](https://user-images.githubusercontent.com/39090271/52839987-d6009900-3132-11e9-869e-b21b5e8a45cb.png)
    @yangxue0827 请教一下大神，不知道这个问题该怎么解决的？

**Comment by yangxue0827** [comment]
这个函数不能产生多级目录，你换成产生多级目录的函数就行，好像是os.path.mkdirs @1451595897

**Comment by 1451595897** [comment]
把函数改为os.makedirs，问题就解决了，非常感谢！ @yangxue0827
