### ISSUE TITLE
如何使用vgg16作为预训练模型

### ISSUE THREAD

**Issue by chaojixiaohaizei** [DetectionTeamUCAS/FPN_Tensorflow#49]
您好，博主，我想用vgg16代替resnet，我看networks里面有vgg.py，请问该如何修改代码

**Comment by yangxue0827** [comment]
建议用tensorflow官方slim给的vgg脚本和权重 @chaojixiaohaizei

**Comment by chaojixiaohaizei** [comment]
博主，您好，除了使用TensorFlow官方的脚本和权重以外，在FPN_Tensorflow代码里，还需要修改其他代码吗？比如build_rpn.py，请问博主知道该如何修改吗？

**Comment by yangxue0827** [comment]
你只要把特征图都返回出来就行，其他都一样操作 @chaojixiaohaizei
