### ISSUE TITLE
does it support multiple gpus?

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [DetectionTeamUCAS/FPN_Tensorflow#5]
does it support multiple gpus?

**Comment by yangxue0827** [comment]
No, you need to write by yourself.

**Comment by Ixiaohuihuihui** [comment]
thank you a lot

**Comment by yangxue0827** [comment]
refer [here](https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/multi_gpu_train.py)

**Comment by heiyuxiaokai** [comment]
@yangxue0827 请问多gpu训练的速度和精度怎么样，我自己也实现了一下，速度大概只有单张gpu的1.6倍，精度会下降3-4个百分点。不过正则化损失那里实现有些不同，我会改一改再试一下

**Comment by yangxue0827** [comment]
在coco上精度一样，在readme的折线图我给了精度的比较 @heiyuxiaokai

**Comment by heiyuxiaokai** [comment]
那速度呢 @yangxue0827

**Comment by yangxue0827** [comment]
没具体测，快是快了的 @heiyuxiaokai

**Comment by heiyuxiaokai** [comment]
好的谢谢了，精度可能是由于我实现细节的问题 @yangxue0827

**Comment by Ixiaohuihuihui** [comment]
> refer [here](https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/multi_gpu_train.py)
Thank you very much for your reply! When I study this code, I found that
in line 107 of the file "multi_gpu_train.py", the DECAY_STEP index is out of range,
while in line 145 of the file "cfgs.py", the DECAY_STEP = [60000, 80000].

**Comment by yangxue0827** [comment]
DECAY_STEP = [60000, 80000, 120000] @Ixiaohuihuihui

**Comment by Ixiaohuihuihui** [comment]
I got it, thank you! @yangxue0827

**Comment by heiyuxiaokai** [comment]
@yangxue0827 作者有没有在dota数据集上使用过多gpu训练，我自己实现的版本和你写的版本都比单gpu低6个百分点左右

**Comment by yangxue0827** [comment]
我确实跑出来也不高 @heiyuxiaokai 但是coco上又是一样的，不清楚哪里出了问题
