### ISSUE TITLE
No detection

### ISSUE THREAD

**Issue by blueclowd** [DetectionTeamUCAS/FPN_Tensorflow#52]
Hello, 

I test the pretrained models with  VOC2007 dataset while got no detection at all. I checked by print out the detection boxes from show_boxes = detected_boxes[show_indices] in inference.py but always got empty set. Please advise, thanks

**Comment by blueclowd** [comment]
I found that the model actually detect something with very low confidence (mostly less than 0.1) while the default SHOW_SCORE_THRESHOLD value are much higher than the mean confidence. Any possible reason? Thanks

**Comment by yyvettey** [comment]
I have same problem here. Look forward to your answers.

**Comment by yangxue0827** [comment]
ensure you have loaded trained weight not pretrained weight. @blueclowd @yyvettey
