### ISSUE TITLE
关于生成的anchor

### ISSUE THREAD

**Issue by ttianwang** [DetectionTeamUCAS/FPN_Tensorflow#55]
你好，我对生成的anchor那边有点疑问，希望能够帮助一下，就是在anchor_utils文件中，直接运行的话，出来的结果是这样的，
![image](https://user-images.githubusercontent.com/42958432/54247862-84063400-4575-11e9-9f68-5ec5d82a57ff.png)，我想问一下，这个负值是什么意思啊，为什么会出现负值，这个数组包含的信息应该是中间点位置以及生成的anchors的宽和高吧，那为什么生成的检测框的宽高会大于输入特征图的宽和高啊，谢谢

**Comment by yangxue0827** [comment]
这个是原图上的坐标 @ttianwang

**Comment by ttianwang** [comment]
谢谢，还有一个问题，生成的检测框是原图上的坐标的话，谁的坐标点算是（0,0）呢 @yangxue0827

**Comment by yangxue0827** [comment]
图片左上角 @ttianwang

**Comment by ttianwang** [comment]
好的，谢谢，所以后面还有步骤，是对生成的检测框进行一定的操作让他们在图片范围之内是吗 @yangxue0827
