### ISSUE TITLE
VOC2007trainval+VOC2012trainval用於訓練

### ISSUE THREAD

**Issue by 1451595897** [DetectionTeamUCAS/FPN_Tensorflow#56]
你好,我嘗試用VOC2007trainval+VOC2012trainval來生成tfrecord訓練的時候,會出現rpn_loc_loss:nan的情況,這是數據集上的問題呢還是通過修改代碼就可以解決了?想請教一下你的!
![2019-03-15 23-03-30屏幕截图](https://user-images.githubusercontent.com/39090271/54441111-03168a80-4777-11e9-98f0-93938e1dd4dc.png)

**Comment by yangxue0827** [comment]
降低学习率试试 @1451595897

**Comment by 1451595897** [comment]
试了很多组学习率了，降低学习率也是解决不了问题。 @yangxue0827

**Comment by yangxue0827** [comment]
可以询问一下[这里](https://github.com/yangxue0827/FPN_Tensorflow/issues/46#issuecomment-446210993)，有人训练过 @1451595897

**Comment by 1451595897** [comment]
我用Pascal voc2007 trainval生成tfrecord去训练是不会出现发散这个问题的，但用Pascal voc2012 trainval生成tfrecord去训练就会这样，现在还没想明白是什么原因导致的。 @yangxue0827

**Comment by yangxue0827** [comment]
2012的数据格式和2007不太一样，所以可能不能直接用之前的脚本转数据，你需要对比一下格式，然后相应修改一下转数据的脚本。 @1451595897

**Comment by 1451595897** [comment]
比较纳闷的是，Pascal VOC2007和Pascal VOC2012的格式是一样的啊，所以你写的这个转tfrecord的脚本是通用的才对的。

**Comment by cdshdow** [comment]
> 我用Pascal voc2007 trainval生成tfrecord去训练是不会出现发散这个问题的，但用Pascal voc2012 trainval生成tfrecord去训练就会这样，现在还没想明白是什么原因导致的。 @yangxue0827

您好，我用voc2007也报这个错误，您的生成步骤是怎样的，可以指导一下吗？

**Comment by cdshdow** [comment]
> 我用Pascal voc2007 trainval生成tfrecord去训练是不会出现发散这个问题的，但用Pascal voc2012 trainval生成tfrecord去训练就会这样，现在还没想明白是什么原因导致的。 @yangxue0827

您好，我用voc2007也报这个错误，您的生成步骤是怎样的，可以指导一下吗？@1451595897

**Comment by 1451595897** [comment]
@cdshdow  我用voc2007轉換成tfrecord倒是不會出現這個錯誤的,但voc2012才會這樣,生成步驟的話只要按照作者寫的去執行就行了!

**Comment by O-Givenchy** [comment]
> @cdshdow  我用voc2007轉換成tfrecord倒是不會出現這個錯誤的,但voc2012才會這樣,生成步驟的話只要按照作者寫的去執行就行了!

 same problem https://github.com/DetectionTeamUCAS/FPN_Tensorflow/issues/75 

建议不要修改博主的convert脚本，我的做法是修改xml文件。。。 btw 2012的训练集中的2008_*.xml不用修改。。只用改2009，2010 和2011的就行了。

**Comment by cdshdow** [comment]
> @cdshdow 我用voc2007轉換成tfrecord倒是不會出現這個錯誤的,但voc2012才會這樣,生成步驟的話只要按照作者寫的去執行就行了!
是数据集格式的问题，bndbox 2007和2008顺序[xmin,ymin,xmax,ymax]，其它顺序不一致。参见@O-Givenchy的回复

**Comment by cdshdow** [comment]
> > @cdshdow  我用voc2007轉換成tfrecord倒是不會出現這個錯誤的,但voc2012才會這樣,生成步驟的話只要按照作者寫的去執行就行了!
> 
> same problem #75
> 
> 建议不要修改博主的convert脚本，我的做法是修改xml文件。。。 btw 2012的训练集中的2008_*.xml不用修改。。只用改2009，2010 和2011的就行了。

谢谢您的回复，果然如您所说
