### ISSUE TITLE
请问下博主大佬，这个能否在windows下运行？

### ISSUE THREAD

**Issue by rw1995** [DetectionTeamUCAS/FPN_Tensorflow#58]
请问下博主大佬，这个能否在windows下运行？

**Comment by rw1995** [comment]
博主，还有一个问题，请问一下，我是在没找到网络层在哪儿书写的，我看了build_whloe_network，但是感觉貌似没有在这个py文件中构建一个FPN网络，请能指点下吗？多谢多谢

**Comment by yangxue0827** [comment]
windows应该可以的。[FPN网络](https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/libs/networks/resnet.py)
