### ISSUE TITLE
我想请教一下，我在训练过程中出现了loss不稳定，总是震荡的现象，请问您遇到过这种现象吗？

### ISSUE THREAD

**Issue by memeda2232** [DetectionTeamUCAS/FPN_Tensorflow#59]

**Comment by chaojixiaohaizei** [comment]
您好，层主，我也遇见类似情况，loss值一直在0.6-1之间震荡，我一共跑了50000次，loss一直没有收敛，最后的模型效果也不好，请问您解决这个问题了吗？@memeda2232

**Comment by memeda2232** [comment]
没有 还在振荡

**Comment by chaojixiaohaizei** [comment]
请问您一共跑了多少次，你自己改参数了没，还有我想问一下在faster rcnn中roi_bg_threshold_high,roi_bg_threshold_low在本文代码中都对应啥

**Comment by memeda2232** [comment]
跑了300000次 主要修改了学习率 源码我还没有仔细读所以我也不知道

**Comment by chaojixiaohaizei** [comment]
EPSILON = 1e-5，是这个吗，请问你是改大还是改小了，改成多少了，

**Comment by memeda2232** [comment]
不是 是LR  改到0.00001了

**Comment by chaojixiaohaizei** [comment]
您好，请问改小anchor,是这个吗BASE_ANCHOR_SIZE_LIST，

**Comment by PURE-melo** [comment]
请问您现在损失值收敛了吗

**Comment by yangxue0827** [comment]
我之前用这个代码跑过voc2007、voc2012、coco、bdd100k、dota基本没有出现nan，有也是降低一下学习率就好了，所以如果训练自己的数据集可能要根据数据特性调一下参数了。

**Comment by yangxue0827** [comment]
loss震荡在这个代码挺正常的，更苦我的经验就是loc  loss出了最开始比较大，后面就变得比较小然后全程震荡了。如果效果不好，可能就是这个代码在这个数据集不太work，或者参数没有调好。

**Comment by PURE-melo** [comment]
谢谢您的回复！不过我有一个小疑问，我训练了20万步左右，损失值稳定降至 0.67左右，我查看了下损失值的构成，发现这0.67基本都是正则化损失，请问为什么正则化损失降不下去并且维持在0.67这样一个数值呢？ 705286770 邮箱705286770@qq.com 签名由 网易邮箱大师 定制 在2019年03月21日 13:44，yangxue 写道： loss震荡在这个代码挺正常的，更苦我的经验就是loc loss出了最开始比较大，后面就变得比较小然后全程震荡了。如果效果不好，可能就是这个代码在这个数据集不太work，或者参数没有调好。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by heiyuxiaokai** [comment]
我看Readme.md里面的loss下降趋势很好，收敛很快，后面振荡也在一个很小的范围内振荡。
但是我在使用时，dota数据集测试集mAP有0.768，但是loss还是振荡很大（大概在0.5到1.5之间振荡），感觉没有收敛，也有可能是因为遥感数据集，不知道你有没有碰到过这种情况？
@yangxue0827

**Comment by Dave19950** [comment]
> 我看Readme.md里面的loss下降趋势很好，收敛很快，后面振荡也在一个很小的范围内振荡。
> 但是我在使用时，dota数据集测试集mAP有0.768，但是loss还是振荡很大（大概在0.5到1.5之间振荡），感觉没有收敛，也有可能是因为遥感数据集，不知道你有没有碰到过这种情况？
> @yangxue0827

请问你在dota数据集上的训练有改什么参数吗？为什么我训练出来的效果很差，只有百分之十几。而且loss同样在震荡。

**Comment by yangxue0827** [comment]
@heiyuxiaokai 应该和数据集有关，我在dota上loss也振荡，你是什么都没加就跑到76.8%吗？

**Comment by heiyuxiaokai** [comment]
@yangxue0827 源码能跑到0.71左右吧，自己加了多尺度和OHEM，dota水平框那个榜你0.793的mAP不是用这套代码吗？

**Comment by heiyuxiaokai** [comment]
@Dave19950 基本没改，应该可以到0.71左右，百分之十几应该是有问题的

**Comment by yangxue0827** [comment]
是基于这套代码的，另外之前你说的多gpu训练dota降点的原因找到了吗？ @heiyuxiaokai

**Comment by heiyuxiaokai** [comment]
@yangxue0827 之前低太多是我测试参数有问题，现在双gpu会比单gpu低1个百分点左右，可能需要调下参

**Comment by summerrr** [comment]
> @Dave19950 基本没改，应该可以到0.71左右，百分之十几应该是有问题的

请问下你的参数是怎么设置的，我跑dota用这个才跑了62%左右

**Comment by summerrr** [comment]
请问下你们dota数据集的参数都是怎么设置的啊，我直接跑才跑到了62% 
@Dave19950 @heiyuxiaokai

**Comment by heiyuxiaokai** [comment]
我训练了15个epoch左右，参数基本没改，测试用的划窗的形式 @summerrr

**Comment by summerrr** [comment]
> 我训练了15个epoch左右，参数基本没改，测试用的划窗的形式 @summerrr

那，训练时你是怎么裁剪的，大小是多少，stride是多少

**Comment by heiyuxiaokai** [comment]
窗口1200 重叠300 @summerrr

**Comment by summerrr** [comment]
@heiyuxiaokai 那你总共训练图片大概有多少张啊，把训练和验证集都作为训练集了吗？15个epoch是15万次迭代吗

**Comment by heiyuxiaokai** [comment]
@summerrr 训练和验证都作为训练集了，1个epoch是把所有原始数据训练一次，一共15个epoch，具体迭代次数根据你的数据量

**Comment by clw5180** [comment]
> @summerrr 训练和验证都作为训练集了，1个epoch是把所有原始数据训练一次，一共15个epoch，具体迭代次数根据你的数据量
大佬，请教一下你crop得到的图片总共有多少张？训练15个epoch应该要很久吧.........我crop下来差不多得10多万张，而且作者的模型只支持batchsize=1，一块显卡怕不是要跑十几天才能完事......可否留个联系方式向你请教...

**Comment by ttianwang** [comment]
你好，我想问一下，我也是用的这套代码跑的DOTA数据集，但是我是单目标，只将里面含有飞机的图片拿出来做训练和测试，切的图片是1024*1024的，步长是512，我现在遇到的问题是两次跑出来的结果不相同，能差5%左右，请问你有出现这种情况吗？我是在1080上进行测试的，训练的时候能占8个多g的内存，请问您在训练的时候能占多少呢？ @heiyuxiaokai

**Comment by heiyuxiaokai** [comment]
如果实验环境完全相同，重复试验的结果应该是一样的，检查下哪里有问题。具体显存忘了，之前跑的，11G显存是可以训练的@ttianwang

**Comment by ttianwang** [comment]
那请问您用这套代码是什么都没改跑出来的结果几次都差不多的吗 @heiyuxiaokai

**Comment by heiyuxiaokai** [comment]
你是说两次训练吗，这个就有一定的随机性，但是总体变化不会太大@ttianwang

**Comment by ttianwang** [comment]
> 你是说两次训练吗，这个就有一定的随机性，但是总体变化不会太大@ttianwang

对的，我两次训练结果能差到5%左右，这个就很奇怪 @heiyuxiaokai
