### ISSUE TITLE
你好，有些问题想问一下

### ISSUE THREAD

**Issue by ttianwang** [DetectionTeamUCAS/FPN_Tensorflow#60]
1、因为编译出来的cython_bbox文件好像只能在gpu上使用，请问有没有cpu上可以使用的
2、在配置文件里面，PIXEL_MEAN = [123.68, 116.779, 103.939] 这个一直不懂具体是在干什么

**Comment by yangxue0827** [comment]
1、你可以自己写一个iou的计算脚本替换cython_bbox
2、pretrain model是resnet在imagenet上训练的，在训练过程中图片进行了减均值[123.68, 116.779, 103.939]的操作，这里是为了和与训练权重保持一致。另外减均值有利于加快收敛速度
@ttianwang

**Comment by ttianwang** [comment]
好的，谢谢， @yangxue0827
