### ISSUE TITLE
Hangs indefinitely at sess.run() and ValueError: attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by namrata-simha** [DetectionTeamUCAS/FPN_Tensorflow#61]
**I am unable to start training since it hangs and never returns at this line. Any thoughts?**

https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/9ea554665a127af72698ed7e3bedd5a3fd5db253/tools/multi_gpu_train.py#L326

I am using tensorflow 1.10.0, Cuda 9.0 and Cudnn 7.0 on Ubuntu 16.04.

**Comment by namrata-simha** [comment]
I got past this issue when I reset and reinstalled my environment, but now I have the same problem as #53 on a custom dataset, do you think it's a problem with my tfrecord?

**Comment by dsj1840923452** [comment]
1

**Comment by dsj1840923452** [comment]
hello, I have the same problem as #53 on a custom dataset,how did you solve it?

**Comment by namrata-simha** [comment]
@dsj1840923452 Turns out my tfrecord was corrupt when I tried that. I regenerated it and it worked.

**Comment by Rachquazar** [comment]
I have been trying out this code for my custom and keep getting the same error. I regenerated the tfrecord file but no use. Any suggestions?

The error is as follows:

  **File "../libs/detection_oprations/anchor_target_layer_without_boxweight.py", line 53, in anchor_target_layer
    argmax_overlaps = overlaps.argmax(axis=1)

ValueError: attempt to get argmax of an empty sequence**
