### ISSUE TITLE
Request for the trained model on the COCO dataset. 

### ISSUE THREAD

**Issue by wangywUST** [DetectionTeamUCAS/FPN_Tensorflow#63]
Thanks for your contribution on this implementation, very efficient and helpful. But I really hope that you can share the trained models, i.e. .ckpt files, trained on the COCO trainval35 dataset, which is much more hard than training on the Pascal VOC dataset. Look forward to your replies!

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/NAS_FPN_Tensorflow. @wangywUST
