### ISSUE TITLE
faster-RCNN mobilenet_v2中是否加入fpn?

### ISSUE THREAD

**Issue by QiaoranC** [DetectionTeamUCAS/FPN_Tensorflow#64]
想问一下:
faster-RCNN mobilenet_v2里面有集成fpn进去么?
如果没有,是不是理论上不可行?
那mobilenet_v1可行吗?

因为, tf官方的object detector里面有 ssd_mobilenet_v2/v1_fpn_feature_extractor,
也没有faster rcnn mobile net v1/2 fpn的.

**Comment by rw1995** [comment]
其實我也想知道
