### ISSUE TITLE
一些思想想不明白

### ISSUE THREAD

**Issue by rw1995** [DetectionTeamUCAS/FPN_Tensorflow#69]
您好，我在make_anchors这个函数位置是产生了疑惑
问题定位在anchor_utils.py中有一段代码是这么写的
1. x_centers = tf.range(featuremap_width, dtype=tf.float32) * stride
2.y_centers = tf.range(featuremap_height, dtype=tf.float32) * stride

3.if cfgs.USE_CENTER_OFFSET:
          x_centers = x_centers + stride/2.
          y_centers = y_centers + stride/2.

4. x_centers, y_centers = tf.meshgrid(x_centers, y_centers)
5. ws, x_centers = tf.meshgrid(ws, x_centers)
6. hs, y_centers = tf.meshgrid(hs, y_centers)

对于1. 2. 我可以理解为是各个特征图对应原图的anchorbox的特征中心吗？
但是我不是很明白4. 5. 6.中为何使用tf.meshgrid这个函数？
求指教 @yangxue0827 @yangJirui @toubasi

**Comment by yangxue0827** [comment]
1. 2 是特征图上的特征点映射到原图的位置，此时并没有产生所有特征点的坐标
4. 5. 6.使用tf.meshgrid是为了产生所有特征点在原图上的坐标（网格状）
建议使用numpy进行debug，方便理解，tf中这些函数numpy中都有 @rw1995

**Comment by rw1995** [comment]
哇，多谢多谢，我已经用numpy去测试了，确实如此，~~多谢多谢
