### ISSUE TITLE
不好意思，您好，我又产生了一些问题

### ISSUE THREAD

**Issue by rw1995** [DetectionTeamUCAS/FPN_Tensorflow#71]
在encode_and_decode.py中有这么一段代码：
`t_xcenter, t_ycenter, t_w, t_h = tf.unstack(encoded_boxes, axis=1)
    if scale_factors:
        t_xcenter /= scale_factors[0]
        t_ycenter /= scale_factors[1]
        t_w /= scale_factors[2]
        t_h /= scale_factors[3]
`
您好，我对使用t_xcenter产生的predictx_center等不是很明白，尽管在论文中确实公式是如此，但是对于predict_xcenter,我发现这这样的：
`t_xcenter, t_ycenter, t_w, t_h = tf.unstack(encoded_boxes, axis=1)`
而encode_boxer追到代码中是
`encoded_boxes=rpn_bbox_pred`
rpn_bbox_pred，我在阅读代码时认为是 对卷积后的特征图进行预测的目标框的位置信息？
这理解起来就不对啊博主。
难道我应该理解在build_whloe_network.py中这段代码：
`rpn_box_pred = slim.conv2d(rpn_conv3x3, self.num_anchors_per_location*4, [1, 1], stride=1,
                                           trainable=self.is_training, weights_initializer=cfgs.BBOX_INITIALIZER,
                                           activation_fn=None, padding="VALID",
                                           scope=scope_list[2],
                                           reuse=reuse_flag)`
这段代码是预测框与真实框的偏差？
望指教

**Comment by yangxue0827** [comment]
预测的是偏移量，但是并不是直接是预测框与真实框的偏差，需要经过编解码过程，也就是论文里提的线性操作。 @rw1995
