### ISSUE TITLE
在运行评价网络时报错

### ISSUE THREAD

**Issue by fanfan00** [DetectionTeamUCAS/FPN_Tensorflow#72]
InternalError (see above for traceback): WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true / nonzero indices.  temp_storage_bytes: 1, status: invalid configuration argument
	 [[Node: assign_levels/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](assign_levels/Equal)]]
	 [[Node: postprocess_fastrcnn/unstack_1/_1279 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4321_postprocess_fastrcnn/unstack_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by unlabeledData** [comment]
Do you know how to solve this problem?
