### ISSUE TITLE
运行readme中demo命令时报错：AttributeError: module 'tensorflow.compat' has no attribute 'v1'

### ISSUE THREAD

**Issue by Kcnco1998** [DetectionTeamUCAS/FPN_Tensorflow#73]
tensorflow版本：1.10.0
python版本：3.5.4

在运行demo命令
```   
cd $PATH_ROOT/tools
python inference.py --data_dir='/PATH/TO/IMAGES/' 
                    --save_dir='/PATH/TO/SAVE/RESULTS/' 
                    --GPU='0'
```
时发生报错：
Traceback (most recent call last):
  File "inference.py", line 17, in <module>
    from libs.networks import build_whole_network
  File "../libs/networks/build_whole_network.py", line 10, in <module>
    from libs.networks import resnet
  File "../libs/networks/resnet.py", line 12, in <module>
    import tfplot as tfp
  File "/home/zhangjr/anaconda3/envs/FPN/lib/python3.5/site-packages/tfplot/__init__.py", line 14, in <module>
    from . import summary
  File "/home/zhangjr/anaconda3/envs/FPN/lib/python3.5/site-packages/tfplot/summary.py", line 14, in <module>
    summary_image_v1 = tf.compat.v1.summary.image
AttributeError: module 'tensorflow.compat' has no attribute 'v1'

请问该如何解决？谢谢。

**Comment by yangxue0827** [comment]
安装tfplot或者屏蔽相关可视化代码@Kcnco1998

**Comment by Kcnco1998** [comment]
@yangxue0827 tfplot之前已安装，只是import tfplot时会出错。查了下好像是tensorflow版本不够的问题，tensorflow.compat.v1是在tensorflow2.0预览版（tf 2.0 previw）中提供的，如果升级至tf 2.0 previw，能否兼容该网络代码？
pip install --upgrade tf-nightly-2.0-preview

**Comment by fanfan00** [comment]
安装tfplot0.2.0，不要安装0.3.1

**Comment by Kcnco1998** [comment]
@yangxue0827 感谢 修改tfplot版本后能跑完demo了，但输出到目标文件夹中的图片都是原图，并没有mask框及value，以下是部分运行信息：
model restore from pretrained mode, path is : /home/zhangjr/FPN_Tensorflow-master_0513/data/pretrained_weights/resnet_v1_50.ckpt
var_in_graph:  resnet_v1_50/block2/unit_3/bottleneck_v1/conv2/BatchNorm/moving_variance:0
var_in_ckpt:  resnet_v1_50/block2/unit_3/bottleneck_v1/conv2/BatchNorm/moving_variance
之后所有的var_in_graph也全都是0

**Comment by yangxue0827** [comment]
你加载的是需训练权重，当然没有结果。请下载提供的trained model，并放在相应的位置 @Kcnco1998

**Comment by Dalal1983** [comment]
I solved this problem by remove `v1.summary` to be like this:
`summary_image_v1 = tf.compat.image`

**Comment by laura400** [comment]
我下载了提供的train model，但是是4个文件，我只改动了文件名称为resnet_v1_101，并且用了对应的resnet_v1_101 的cfgs_res101_fpn_v1.py 复制到了cfgs.py中，但是仍然权重和variance都是0，这个是要改动什么或者如何导入4个ckpt相关文件呢？

**Comment by Kcnco1998** [comment]
@yangxue0827 提供的trained model指的是https://github.com/DetectionTeamUCAS/Models/tree/master/FPN_Tensorflow这两个model么，解压之后是各有四个文件checkpoint，.data-00000-of-00001,.index,.meta的模型结构，而cfgs.py中输入weights_name等步骤中，需要的似乎都是单个的.ckpt文件，请问对于这四个文件要怎么去引用处理呢？

**Comment by Kcnco1998** [comment]
@yangxue0827 提供的trained model指的是https://github.com/DetectionTeamUCAS/Models/tree/master/FPN_Tensorflow 这两个model么，解压之后是各有四个文件checkpoint，.data-00000-of-00001,.index,.meta的模型结构，而cfgs.py中输入weights_name等步骤中，需要的似乎都是单个的.ckpt文件，请问对于这四个文件要怎么去引用处理呢？

**Comment by Kcnco1998** [comment]
@Dalal1983 Thanks，I also have sovled the problem by changing my tfplot version from 0.3.1 to 0.2.0.
