### ISSUE TITLE
您好，如果在自己的数据集上训练，各类别的比例不均匀，为获得更好的性能需要怎么给不同类别loss加权？

### ISSUE THREAD

**Issue by captaincj** [DetectionTeamUCAS/FPN_Tensorflow#74]
我目前的数据集是RTTS带雾数据集，一共只有5类，4300张带标注的图片，数据集中有些类别很少，取80%作为训练集的话只有600个目标。
我希望通过对不同类别的的loss加权的方法提升某些类别的mAP， 具体应该在哪些地方修改loss呢？
以及修改loss会不会对网络的训练造成很大影响？

**Comment by yangxue0827** [comment]
或者你可以参考focal loss的想法 @captaincj
