### ISSUE TITLE
roi pooling

### ISSUE THREAD

**Issue by rw1995** [DetectionTeamUCAS/FPN_Tensorflow#76]
你好，博主，关于在build_whole_network.py中的第5步，roi_pooling过程中我发现您使用的是
`cropped_roi_features = tf.image.crop_and_resize(feature_maps, normalized_rois,
                                                            box_ind=tf.zeros(shape=[N, ],
                                                                             dtype=tf.int32),
                                                            crop_size=[cfgs.ROI_SIZE, cfgs.ROI_SIZE],
                                                            name='CROP_AND_RESIZE'
                                                            )`
这貌似不是roi_pooling中的最临近差值法，而是默认使用双线性差值?难道是使用的roi_align?

**Comment by yangxue0827** [comment]
是的 @rw1995

**Comment by rw1995** [comment]
你好，請問下這個代碼支持mobilenetV2嗎？我不知道如何使用 @yangxue0827

**Comment by yangxue0827** [comment]
暂时没有支持，修改比较简单，仿照resnet.py里得到P2-P5然后构造fpn结构返回 @rw1995

**Comment by rw1995** [comment]
好的我嘗試下，不得不說，您的進度很快

**Comment by yangxue0827** [comment]
感谢支持 @rw1995
