### ISSUE TITLE
关于训练次数

### ISSUE THREAD

**Issue by ttianwang** [DetectionTeamUCAS/FPN_Tensorflow#77]
你好，我看配置文件中只有max_iteration,没有epoch，这样的话会不会有训练样本训练的比较少，而导致最终结果有差异

**Comment by yangxue0827** [comment]
可以参考https://github.com/DetectionTeamUCAS/NAS_FPN_Tensorflow.git  @ttianwang

**Comment by ttianwang** [comment]
好的，谢谢 @yangxue0827
