### ISSUE TITLE
Train on CUDA10, stuck in 'sess.run'

### ISSUE THREAD

**Issue by 0fine0** [DetectionTeamUCAS/FPN_Tensorflow#79]
I trained the model on COCO dataset with CUDA 10.
However, the code is stuck at 'sess.run'
Wtihout any error, the code can not move on.
What shall I do?

**Comment by baokelion** [comment]
> I trained the model on COCO dataset with CUDA 10.
> However, the code is stuck at 'sess.run'
> Wtihout any error, the code can not move on.
> What shall I do?

do you solve the error?

**Comment by 0fine0** [comment]
> > I trained the model on COCO dataset with CUDA 10.
> > However, the code is stuck at 'sess.run'
> > Wtihout any error, the code can not move on.
> > What shall I do?
> 
> do you solve the error?

I suppose that should be tfrecord file's fault and I made some mistake while creating the tfrecord file. If you didn't change the code, I suggest you to check tfrecord file.

**Comment by baokelion** [comment]
thank you very much




------------------ 原始邮件 ------------------
发件人: "0fine0"<notifications@github.com>;
发送时间: 2019年8月13日(星期二) 上午8:48
收件人: "DetectionTeamUCAS/FPN_Tensorflow"<FPN_Tensorflow@noreply.github.com>;
抄送: "bk"<baokelion@foxmail.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [DetectionTeamUCAS/FPN_Tensorflow] Train on CUDA10, stuck in'sess.run' (#79)




Closed #79.

**Comment by baokelion** [comment]
Thank you very much, I have solved the problem according to your suggestion.




------------------ 原始邮件 ------------------
发件人: "0fine0"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 上午8:48
收件人: "DetectionTeamUCAS/FPN_Tensorflow"<FPN_Tensorflow@noreply.github.com>; 
抄送: "bk"<baokelion@foxmail.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [DetectionTeamUCAS/FPN_Tensorflow] Train on CUDA10, stuck in'sess.run' (#79)



  
I trained the model on COCO dataset with CUDA 10.
 However, the code is stuck at 'sess.run'
 Wtihout any error, the code can not move on.
 What shall I do?
  
do you solve the error?
  
I suppose that should be tfrecord file's fault and I made some mistake while creating the tfrecord file. If you didn't change the code, I suggest you to check tfrecord file.

**Comment by tienhoang1094** [comment]
how u fixit, plz tell me

**Comment by 0fine0** [comment]
> how u fixit, plz tell me

read the dialogue

**Comment by tienhoang1094** [comment]
i have read it but i cant open tfrecord file, so can;t check

**Comment by tienhoang1094** [comment]
my record create sucsses but 0 byte .

**Comment by 0fine0** [comment]
> my record create sucsses but 0 byte .

that means you didn't create a useful tfrecord file.

If you didn't change anything in the code, I suggest you check the corresponding path to dataset.

**Comment by tienhoang1094** [comment]
the path lost '/' in parameter img and xml dir! solved ! thank u

**Comment by tienhoang1094** [comment]
![image](https://user-images.githubusercontent.com/58082063/71390239-23427680-2632-11ea-9484-eaa988b4c4d2.png)
this wrong path actually doesnt exsit but this alert dont show ...
