### ISSUE TITLE
您好，我在训练过程中，在tensorboard上面观察训练结果，起初是有框的，在训练1000次左右之后，就没有框了

### ISSUE THREAD

**Issue by lilmangolil** [DetectionTeamUCAS/FPN_Tensorflow#8]
您好，如标题所说，在训练起初是可以看到训练框的，之后看不到训练框了，请问可能是什么原因呢？另外，layer5的热图总是看起来像是单颜色，请问这样是正常的吗？

**Comment by yangxue0827** [comment]
贴一下图例 @lilmangolil

**Comment by lilmangolil** [comment]
> 贴一下图例 @lilmangolil
![1544148314](https://user-images.githubusercontent.com/45140199/49623334-2effd280-fa08-11e8-87bb-d2f2c41063be.jpg)
您好，图是这样的，可能刚才没上传成功，谢谢回复(*^▽^*)

**Comment by yangxue0827** [comment]
你先多训练一会吧，如果voc的结果没问题了，换个数据集应该问题不大。 @lilmangolil

**Comment by lilmangolil** [comment]
> 你先多训练一会吧，如果voc的结果没问题了，换个数据集应该问题不大。 @lilmangolil

您好，训练完70000次了，还是没有框，我是训练的是含有3000张图片的人脸数据库，cfg.py中修改了参数：BASE_ANCHOR_SIZE_LIST = [16,32, 64, 128, 256]，ANCHOR_STRIDE_LIST = [4 ,8 , 16 , 32, 64]，不知是否是这个的原因呢？在您之前版本的FPN-tensorflow中用这组参数训练是有框的。望您解答，谢谢(#^.^#)

**Comment by yangxue0827** [comment]
ANCHOR_STRIDE_LIST改成了多少，这个一般不能改 @lilmangolil

**Comment by rw1995** [comment]
> > 你先多训练一会吧，如果voc的结果没问题了，换个数据集应该问题不大。 @lilmangolil
> 
> 您好，训练完70000次了，还是没有框，我是训练的是含有3000张图片的人脸数据库，cfg.py中修改了参数：BASE_ANCHOR_SIZE_LIST = [16,32, 64, 128, 256]，ANCHOR_STRIDE_LIST = [4 ,8 , 16 , 32, 64]，不知是否是这个的原因呢？在您之前版本的FPN-tensorflow中用这组参数训练是有框的。望您解答，谢谢(#^.^#)

你好，请问下您是怎么实现训练的，我在Modify parameters (such as CLASS_NUM, DATASET_NAME, VERSION, etc.) in $PATH_ROOT/libs/configs/cfgs.py 这个环节上出现了问题，能说下您的操作过程吗？

**Comment by Levigty** [comment]
@lilmangolil @yangxue0827 您们好，我也遇到了类似的问题。代码的效果很不错，在voc数据集上mAP: 76.91。换了自己的一个缺陷数据集（750张图片，500train，250test）mAP接近100%。问题是当我对这750张图像进行水平Flip和垂直Filp最后增强到3000张图像再跑同样的网络后，mAP为0。tensorboard可视化后也是没有框，更奇怪的是热图全白，而且FPN的ACC震荡特别厉害。我检查过了数据增强后的数据集，bbox没有问题。为什么增强前mAP100，增强后直接不work了。这是什么原因造成的呢，我觉得对于缺陷目标这种增强应该没这么大影响吧？还是LR太高？我会先降低一下LR试一下，也期待您们的见解和回复。
![abc](https://user-images.githubusercontent.com/47876324/70323019-af991f00-1866-11ea-8e3c-2e29c261e986.JPG)
