### ISSUE TITLE
运行setup.py时出错

### ISSUE THREAD

**Issue by VaryCuteStitch** [DetectionTeamUCAS/FPN_Tensorflow#80]
D:\anaconda3.6\python.exe "F:/yllcode/FPN_Tensorflow-master (1)/FPN_Tensorflow-master/libs/box_utils/cython_utils/setup.py"
Traceback (most recent call last):
  File "F:/yllcode/FPN_Tensorflow-master (1)/FPN_Tensorflow-master/libs/box_utils/cython_utils/setup.py", line 56, in <module>
    CUDA = locate_cuda()
  File "F:/yllcode/FPN_Tensorflow-master (1)/FPN_Tensorflow-master/libs/box_utils/cython_utils/setup.py", line 53, in locate_cuda
    raise EnvironmentError('The CUDA %s path could not be located in %s' % (k, v))
OSError: The CUDA nvcc path could not be located in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc
百度过都没有这个问题，调过环境变量也没用。
请问楼主出现过这个问题没，该怎么解决

**Comment by rw1995** [comment]
我用的ubuntu16没有这个问题

**Comment by leiyaohui** [comment]
Hello, I met the same problem. Have you solved it?

**Comment by VaryCuteStitch** [comment]
No, our teacher said that it may be because the computer system is wrong, I am running under Windows, you can try it under Linux system.






------------------ 原始邮件 ------------------
发件人: "leiyaohui"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 下午5:32
收件人: "DetectionTeamUCAS/FPN_Tensorflow"<FPN_Tensorflow@noreply.github.com>;
抄送: "暖暖"<409297468@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DetectionTeamUCAS/FPN_Tensorflow] 运行setup.py时出错 (#80)




Hello, I met the same problem. Have you solved it?

**Comment by VaryCuteStitch** [comment]
谢谢，我正在重装系统与配置环境。





------------------ 原始邮件 ------------------
发件人: "rw1995"<notifications@github.com>;
发送时间: 2019年6月15日(星期六) 中午1:44
收件人: "DetectionTeamUCAS/FPN_Tensorflow"<FPN_Tensorflow@noreply.github.com>;
抄送: "暖暖"<409297468@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DetectionTeamUCAS/FPN_Tensorflow] 运行setup.py时出错 (#80)




我用的ubuntu16没有这个问题
