### ISSUE TITLE
关于gt分配

### ISSUE THREAD

**Issue by ttianwang** [DetectionTeamUCAS/FPN_Tensorflow#82]
你好，我想问一下，在给锚框分配gt时，能保证每一个gt都被分配到至少一个锚框吗？看代码实现时，感觉可能存在gt未被分配锚框的情况。

**Comment by yangxue0827** [comment]
rpn阶段有一个策略是与gt有最大iou的anchor是正样本，详细可以看faster论文 @ttianwang
