### ISSUE TITLE
关于AP

### ISSUE THREAD

**Issue by ttianwang** [DetectionTeamUCAS/FPN_Tensorflow#84]
你好，我想问一下，在对每一类进行AP计算的时候，该类里面出现置信度为0的框，但是该框确确实实是该类别，这种情况下，这个框算是被检测到了还是未被检测到啊，例如下图，框中的物体的确是飞机，但是置信度却很低，那在代码中算是tp还是fp呢？我看代码的理解感觉是tp，不知道我的理解对不对
![image](https://user-images.githubusercontent.com/42958432/60653238-3f800a80-9e7c-11e9-80bf-bdaae90a4ebb.png)

**Comment by yangxue0827** [comment]
对的 @ttianwang
