### ISSUE TITLE
about next_batch size 

### ISSUE THREAD

**Issue by chenhangcal** [DetectionTeamUCAS/FPN_Tensorflow#85]
https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/9ea554665a127af72698ed7e3bedd5a3fd5db253/tools/multi_gpu_train.py#L118

Here batch_size=cfgs.BATCH_SIZE * num_gpu, but later only the first num_gpu images fed the network, if BATCH_SIZE >1, the rest of the images were wasted. So why not just set batch_size=num_gpu?

**Comment by yangxue0827** [comment]
这个是为了方便以后多batch size和多gpu代码留的
