### ISSUE TITLE
Batch size can only be set 1?

### ISSUE THREAD

**Issue by zpge** [DetectionTeamUCAS/FPN_Tensorflow#88]
In this repo, the bacth size can only be 1?

**Comment by yangxue0827** [comment]
yes

**Comment by zpge** [comment]
> yes

Thanks for your reply. If I train with my own data, will it greatly affect the converge speed?

**Comment by yangxue0827** [comment]
a little @zpge

**Comment by zpge** [comment]
> little
OK. Thanks.
