### ISSUE TITLE
请求改进建议

### ISSUE THREAD

**Issue by csolfh** [DetectionTeamUCAS/FPN_Tensorflow#89]
GTbox：
![傲游截图20190708111925](https://user-images.githubusercontent.com/42266762/60780816-8454bb80-a172-11e9-8072-d740eccc9226.jpg)

![傲游截图20190708112002](https://user-images.githubusercontent.com/42266762/60780821-8a4a9c80-a172-11e9-8eb4-77fab5bd3570.jpg)

![傲游截图20190708112011](https://user-images.githubusercontent.com/42266762/60780834-97678b80-a172-11e9-880f-9ea5c5f48d0f.jpg)

原图中的目标尺度比较小，我应该如何改进网络参数

**Comment by yangxue0827** [comment]
anchor改小一点
