### ISSUE TITLE
cuda8.0

### ISSUE THREAD

**Issue by 1451595897** [DetectionTeamUCAS/FPN_Tensorflow#9]
你好，假如说我还是想用cuda8.0的，而不想再安装一个cuda9.0来切换，该如何设置cfgs.py呢？

**Comment by doublemanyu** [comment]
将CUDA9 = True改为False,项目中有提示的

**Comment by chaojixiaohaizei** [comment]
@doublemanyu 你好，我将CUDA9 = True改为False还是报错，‘the nvcc binary could not be'，请问是什么原因’
