### ISSUE TITLE
 no CUDA-capable device is detected

### ISSUE THREAD

**Issue by BigWilky** [DetectionTeamUCAS/FPN_Tensorflow#91]
tf.__version__=1.13.1
CUDA Version 10.0.130
cudnn=7.5
GPU=RTX2080
我在训练的时候发现模型使用的是cpu进行的训练,并没有用到gpu，我再配置里需要进行怎么样的配置才可以转换为GPU模式？

**Comment by yangxue0827** [comment]
cfgs.py中的GPU GROUP参数 @BigWilky

**Comment by BigWilky** [comment]
成了！！
非常感谢！！
