### ISSUE TITLE
再训练和生成tfrecord相关问题

### ISSUE THREAD

**Issue by frank-chan-ck** [DetectionTeamUCAS/FPN_Tensorflow#93]
有几个问题再请教一下大神。
第一，用convert_data_to_tfrecord.py 将62G数据集（20W张大小不一的图片）转换为tfrecord过程花了38小时，结果有450G左右。过程有点漫长， 请问这个时间正常么？有没有改善的方法？
第二，因为时间关系，训练第一步中生成的tfrecord过程中，只把max_iteration设置为80000，现在出现loss震荡（多GPU训练），后面想在80000步这个基础上修改LR=0.0003继续训练，是不是将build_whole_network.py中函数get_restorer里的checkpoint_path 修改为上一次训练保存的ckpt路径即可？

**Comment by yangxue0827** [comment]
1.我提供的转换函数输出是会比原来大很多，如果你的数据太大可以把供数据的代码改成placeholder的形式
2.中间代码停了不需要改什么，接着运行会加在最新保存的模型的，只要你不改cfgs里的版本号 @LowWisdom

**Comment by yangxue0827** [comment]
参考  https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/train_with_placeholder.py   @LowWisdom

**Comment by frank-chan-ck** [comment]
> 1.我提供的转换函数输出是会比原来大很多，如果你的数据太大可以把供数据的代码改成placeholder的形式
> 2.中间代码停了不需要改什么，接着运行会加在最新保存的模型的，只要你不改cfgs里的版本号 @LowWisdom

非常感谢！另外，再请教一下：IMG_MAX_LENGTH和IMG_SHORT_SIDE_LEN两个参数的设置问题。我的训练样本图片大小不一，但是大多数都在1024*1024以内，所以将这两个参数都设置为1024。训练完后测试效果，试了好几张照片，出现预测的box超过图片大小范围而没法正常draw box in image。请问这个现象跟这两个参数大小有关系么？如果我用别的脚本生成标准tfrecord，能继续用你的模型训练么？

**Comment by yangxue0827** [comment]
你只要能读出来数据就行，什么样的形式都没关系的 @LowWisdom

**Comment by frank-chan-ck** [comment]
> 你只要能读出来数据就行，什么样的形式都没关系的 @LowWisdom
非常感谢，draw_box的问题已经解决，因为类别数超出颜色列表范围。再请教一下，我的数据集有20W张图片，在BATCH_SIZE=1情况下MAX_ITERATION>=20W才能遍历所有样本是吧？
另外，我在用eval.py程序过程中发现，评价数据集大概38000张（12G左右），生成的 "det_"+cls+".txt" 系列文件结果竟然高达100多G，存文件再读取文件的时间比前面检测图片的时间还长。

**Comment by yangxue0827** [comment]
你卡一个阈值减少分数低的框 @LowWisdom

**Comment by frank-chan-ck** [comment]
> 你卡一个阈值减少分数低的框 @LowWisdom
原来如此，多谢，下次试试看。
今天我尝试将优化算法momentum修改为adam重新训练，修改了multi_gpu_train.py中的一行：optimizer = tf.train.AdamOptimizer(lr)
系统报错，请问还需要修改哪里？
