### ISSUE TITLE
使用自己的数据集训练时卡在restore model

### ISSUE THREAD

**Issue by siyangbing** [DetectionTeamUCAS/FPN_Tensorflow#94]
使用自己的数据集训练时卡在restore model 我使用的是一块1080Ti的显卡,但是显存占用只有两G,不知道哪里有问题,我用你们提供的模型测试是可以的,我想知道如何开始训练我自己的模型

**Comment by yangxue0827** [comment]
可能是你生成的tfrecord里没有数据，检查一下。 @siyangbing
