### ISSUE TITLE
我想把训练好的模型部署到linux终端,我想把模型保存为pb模型,而不是仅仅保存权重!

### ISSUE THREAD

**Issue by siyangbing** [DetectionTeamUCAS/FPN_Tensorflow#95]
我需要如何保存整个网络,如何生成pb文件从而把模型部署到终端(tensorlite),我需要如何保存哪些内容,非常感谢!

**Comment by BigWilky** [comment]
你是想生成什么样的pb？部署到哪里？

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/FPN_Tensorflow/tree/master/libs/export_pbs

@siyangbing
