### ISSUE TITLE
关于ROI Align的实现

### ISSUE THREAD

**Issue by ZhangYumi** [DetectionTeamUCAS/FPN_Tensorflow#96]
你好，我看了代码里ROI Align的实现，是先利用tf.crop_and_resize函数resize到14x14，然后再max_pooling到7x7，为什么不直接用tf.crop_and_resize函数resize到7x7呢？求解答，谢谢。

**Comment by yangxue0827** [comment]
我参考的别人的写法，具体哪个好我也没有实验过。 @ZhangYumi
