### ISSUE TITLE
输入输出图片尺寸

### ISSUE THREAD

**Issue by AllentDan** [DetectionTeamUCAS/FPN_Tensorflow#99]
作者你好！网上资料说原版faster rcnn输入图片尺寸会根据最大的大小边调整，对于图片尺寸小于设置的，会补成黑色，输出也是。这也符合你给的fpn_voc_2007.gif，里面看起来图片是没有经过warp的，但是demo跑出来结果是被warp了。能请教下是否进行了改动吗？

**Comment by yangxue0827** [comment]
你可以根据输入网络前后的图片大小算出缩放比例，然后把结果进行缩放就行了。
